<?php

namespace Database\Seeders;

use App\Models\Accessory;
use App\Models\AccessoryAttribute;
use App\Models\Attribute;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccessorySeeder extends Seeder
{
    public function run()
    {
        $accessories = [
            [
                'name' => 'Anker PowerLine+ USB-C to USB 3.0 Cable',
                'category_id' => 8, // Accessories category
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Anker'],
                    ['name' => 'Model', 'value' => 'PowerLine+ USB-C'],
                    ['name' => 'Price', 'value' => 350000],
                    ['name' => 'Deal Price', 'value' => 320000],
                    ['name' => 'Sale Price', 'value' => 300000],
                    ['name' => 'Rating', 'value' => 4.7],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 100],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/cables/1/Thumb1.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/cables/1/Thumb1_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/cables/1/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/accessories/cables/1/Image2.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Cable'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'USB-C to USB-A'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'Fast Charging, Nylon Braided'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Aluminum Alloy'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'Android, MacBook, iPad Pro'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'Carrying Pouch'],
                ],
            ],
            [
                'name' => 'Apple USB-C to Lightning Cable 1m',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Apple'],
                    ['name' => 'Model', 'value' => 'USB-C to Lightning Cable 1m'],
                    ['name' => 'Price', 'value' => 490000],
                    ['name' => 'Deal Price', 'value' => 460000],
                    ['name' => 'Sale Price', 'value' => 440000],
                    ['name' => 'Rating', 'value' => 4.8],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 150],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/cables/6/Thumb6.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/cables/6/Thumb6_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/cables/6/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/accessories/cables/6/Image2.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Cable'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'USB-C to Lightning'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'Fast Charging, Durable'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Plastic'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'iPhone, iPad'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'None'],
                ],
            ],
            [
                'name' => 'Samsung EVO Plus MicroSDXC 128GB',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Samsung'],
                    ['name' => 'Model', 'value' => 'EVO Plus MicroSDXC 128GB'],
                    ['name' => 'Price', 'value' => 600000],
                    ['name' => 'Deal Price', 'value' => 570000],
                    ['name' => 'Sale Price', 'value' => 550000],
                    ['name' => 'Rating', 'value' => 4.9],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 200],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/memory/7/Thumb7.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/memory/7/Thumb7_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/memory/7/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/accessories/memory/7/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/accessories/memory/7/Image3.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Memory Card'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'MicroSDXC'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'High Speed, Water-resistant'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Plastic'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'Cameras, Smartphones, Tablets'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'Adapter'],
                ],
            ],
            [
                'name' => 'JBL Quantum Stream Microphone',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'JBL'],
                    ['name' => 'Model', 'value' => 'Quantum Stream'],
                    ['name' => 'Price', 'value' => 2200000],
                    ['name' => 'Deal Price', 'value' => 2100000],
                    ['name' => 'Sale Price', 'value' => 2000000],
                    ['name' => 'Rating', 'value' => 4.8],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 50],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/microphones/8/Thumb8.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/microphones/8/Thumb8_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/microphones/8/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/accessories/microphones/8/Image2.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Microphone'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'USB-C'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'Dual Capsule, RGB Lighting'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Metal'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'Windows, macOS'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'Stand, USB-C Cable'],
                ],
            ],
            [
                'name' => 'Case Logic EVA Shockproof Bag 13"',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Case Logic'],
                    ['name' => 'Model', 'value' => 'EVA Shockproof Bag 13"'],
                    ['name' => 'Price', 'value' => 800000],
                    ['name' => 'Deal Price', 'value' => 750000],
                    ['name' => 'Sale Price', 'value' => 720000],
                    ['name' => 'Rating', 'value' => 4.7],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 90],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/bags/9/Thumb9.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/bags/9/Thumb9_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/bags/9/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/accessories/bags/9/Image2.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Bag'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'None'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'Shockproof, Water-resistant'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'EVA Foam'],
                    ['name' => '[Accessory] Tương thích', 'value' => '13" Laptops, Tablets'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'None'],
                ],
            ],
            [
                'name' => 'Elgato Stream Deck MK.2',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Elgato'],
                    ['name' => 'Model', 'value' => 'Stream Deck MK.2'],
                    ['name' => 'Price', 'value' => 4000000],
                    ['name' => 'Deal Price', 'value' => 3800000],
                    ['name' => 'Sale Price', 'value' => 3700000],
                    ['name' => 'Rating', 'value' => 4.9],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 30],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/streamdeck/10/Thumb10.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/streamdeck/10/Thumb10_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/streamdeck/10/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/accessories/streamdeck/10/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/accessories/streamdeck/10/Image3.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Controller'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'USB-C'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'Customizable Keys, Multi-platform Support'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Plastic'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'Windows, macOS'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'USB-C Cable'],
                ],
            ],
            [
                'name' => 'UGREEN USB-C to HDMI Cable 1.8m',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'UGREEN'],
                    ['name' => 'Model', 'value' => 'USB-C to HDMI 1.8m'],
                    ['name' => 'Price', 'value' => 500000],
                    ['name' => 'Deal Price', 'value' => 470000],
                    ['name' => 'Sale Price', 'value' => 450000],
                    ['name' => 'Rating', 'value' => 4.8],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 120],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/cables/2/Thumb2.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/cables/2/Thumb2_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/cables/2/Image1.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Cable'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'USB-C to HDMI'],
                    ['name' => '[Accessory] Tính năng', 'value' => '4K 60Hz, Nylon Braided'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Aluminum Alloy'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'MacBook, iPad Pro, Windows Laptop'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'Velcro Strap'],
                ],
            ],
            [
                'name' => 'Logitech StreamCam Mounting Kit',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Logitech'],
                    ['name' => 'Model', 'value' => 'StreamCam Mounting Kit'],
                    ['name' => 'Price', 'value' => 1200000],
                    ['name' => 'Deal Price', 'value' => 1100000],
                    ['name' => 'Sale Price', 'value' => 1050000],
                    ['name' => 'Rating', 'value' => 4.9],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 50],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/mount/3/Thumb3.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/mount/3/Thumb3_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/mount/3/Image1.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Mount'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'Standard Tripod Mount'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'Adjustable Angle, Durable Material'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Plastic, Metal'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'Logitech StreamCam'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'Quick Guide'],
                ],
            ],
            [
                'name' => 'Razer Thunderbolt 4 Dock Chroma',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Razer'],
                    ['name' => 'Model', 'value' => 'Thunderbolt 4 Dock Chroma'],
                    ['name' => 'Price', 'value' => 8900000],
                    ['name' => 'Deal Price', 'value' => 8500000],
                    ['name' => 'Sale Price', 'value' => 8300000],
                    ['name' => 'Rating', 'value' => 4.8],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 15],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/docks/4/Thumb4.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/docks/4/Thumb4_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/docks/4/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/accessories/docks/4/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/accessories/docks/4/Image3.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Dock'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'Thunderbolt 4, USB-C'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'RGB Lighting, Multiple USB Ports'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Aluminum'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'Windows, Mac, Laptops'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'Power Adapter, USB-C Cable'],
                ],
            ],
            [
                'name' => 'HyperX ChargePlay Duo for PS5',
                'category_id' => 8,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'HyperX'],
                    ['name' => 'Model', 'value' => 'ChargePlay Duo'],
                    ['name' => 'Price', 'value' => 900000],
                    ['name' => 'Deal Price', 'value' => 850000],
                    ['name' => 'Sale Price', 'value' => 820000],
                    ['name' => 'Rating', 'value' => 4.7],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 80],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/accessories/chargers/5/Thumb5.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/accessories/chargers/5/Thumb5_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/accessories/chargers/5/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/accessories/chargers/5/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/accessories/chargers/5/Image3.jpg'],
                    ['name' => '[Accessory] Loại thiết bị', 'value' => 'Charger'],
                    ['name' => '[Accessory] Kết nối', 'value' => 'Dock Charging'],
                    ['name' => '[Accessory] Tính năng', 'value' => 'Dual Controller Charging'],
                    ['name' => '[Accessory] Chất liệu', 'value' => 'Plastic'],
                    ['name' => '[Accessory] Tương thích', 'value' => 'PlayStation 5 Controllers'],
                    ['name' => '[Accessory] Phụ kiện đi kèm', 'value' => 'Charging Cable'],
                ],
            ]
        ];

        foreach ($accessories as $accessoryData) {
            $accessory = Accessory::create([
                'name' => $accessoryData['name'],
                'category_id' => $accessoryData['category_id'],
            ]);
        
            foreach ($accessoryData['attributes'] as $attr) {
                $attribute = Attribute::firstOrCreate(['name' => $attr['name']]);
                AccessoryAttribute::create([
                    'accessory_id' => $accessory->id,
                    'attribute_id' => $attribute->id,
                    'value' => $attr['value'],
                ]);
            }
        }
    }
}
