<?php

namespace Database\Seeders;

use App\Models\Attribute;
use App\Models\Cpu;
use App\Models\CpuAttribute;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CpuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cpus = [
            [
                'name' => 'Intel Core i5-14400F',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Intel'],
                    ['name' => 'Model', 'value' => 'CPUI14400F'],
                    ['name' => 'Price', 'value' => '5030000'],
                    ['name' => 'Deal Price', 'value' => '4290000'],
                    ['name' => 'Rating', 'value' => '5'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '4090000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-04'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-05'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/Intel/Thumb5.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/Intel/Thumb5.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/Intel/1/Image1.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'LGA1700'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '2500'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '4600'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '6'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '12'],
                    ['name' => '[CPU] Số P-core', 'value' => '6'],
                    ['name' => '[CPU] Số E-core', 'value' => '4'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR4, DDR5'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '65W'],
                    ['name' => '[CPU] Công suất cơ bản', 'value' => '65W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'Intel Turbo Boost, Intel Hyper-Threading'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '10nm'],
                ]
            ],
            [
                'name' => 'Intel Core i7-13700K',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Intel'],
                    ['name' => 'Model', 'value' => 'CPUI713700K'],
                    ['name' => 'Price', 'value' => '12990000'],
                    ['name' => 'Deal Price', 'value' => '11590000'],
                    ['name' => 'Rating', 'value' => '5'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '11290000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-04'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-06'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/Intel/2/Image2.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/Intel/Thumb7.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/Intel/2/Image2.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'LGA1700'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '3300'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '5300'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '16'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '24'],
                    ['name' => '[CPU] Số P-core', 'value' => '8'],
                    ['name' => '[CPU] Số E-core', 'value' => '8'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR4, DDR5'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '125W'],
                    ['name' => '[CPU] Công suất cơ bản', 'value' => '125W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'Intel Turbo Boost, Intel Hyper-Threading'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '10nm'],
                ]
            ],
            [
                'name' => 'Intel Core i9-13900KS',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Intel'],
                    ['name' => 'Model', 'value' => 'CPUI913900KS'],
                    ['name' => 'Price', 'value' => '17990000'],
                    ['name' => 'Deal Price', 'value' => '16590000'],
                    ['name' => 'Rating', 'value' => '5'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '15990000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-04'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-07'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/Intel/3/Image3.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/Intel/Thumb9.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/Intel/3/Image3.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'LGA1700'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '3500'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '6000'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '24'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '32'],
                    ['name' => '[CPU] Số P-core', 'value' => '8'],
                    ['name' => '[CPU] Số E-core', 'value' => '16'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR4, DDR5'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '150W'],
                    ['name' => '[CPU] Công suất cơ bản', 'value' => '150W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'Intel Turbo Boost, Intel Hyper-Threading'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '10nm'],
                ]
            ],
            [
                'name' => 'Intel Core i5-12600K',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Intel'],
                    ['name' => 'Model', 'value' => 'CPUI512600K'],
                    ['name' => 'Price', 'value' => '7990000'],
                    ['name' => 'Deal Price', 'value' => '7490000'],
                    ['name' => 'Rating', 'value' => '4.5'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '7390000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-08'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-10'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/Intel/4/Image4.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/Intel/Thumb5.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/Intel/4/Image4.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'LGA1700'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '3200'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '4900'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '10'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '16'],
                    ['name' => '[CPU] Số P-core', 'value' => '6'],
                    ['name' => '[CPU] Số E-core', 'value' => '4'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR4, DDR5'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '125W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'Intel Turbo Boost, Intel Hyper-Threading'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '10nm'],
                ]
            ],
            [
                'name' => 'Intel Core i3-12100',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Intel'],
                    ['name' => 'Model', 'value' => 'CPUI312100'],
                    ['name' => 'Price', 'value' => '3000000'],
                    ['name' => 'Deal Price', 'value' => '2790000'],
                    ['name' => 'Rating', 'value' => '4'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '2690000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-09'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-11'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/Intel/5/Image5.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/Intel/Thumb3.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/Intel/5/Image5.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'LGA1700'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '3300'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '4400'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '4'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '8'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR4, DDR5'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '60W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'Intel Turbo Boost, Intel Hyper-Threading'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '10nm'],
                ]
            ],
        
            // AMD CPUs
            [
                'name' => 'AMD Ryzen 5 7600',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'AMD'],
                    ['name' => 'Model', 'value' => 'CPUR57600'],
                    ['name' => 'Price', 'value' => '6890000'],
                    ['name' => 'Deal Price', 'value' => '6490000'],
                    ['name' => 'Rating', 'value' => '5'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '6390000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-04'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-06'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/AMD/1/Image6.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/AMD/Thumb5.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/AMD/1/Image6.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'AM5'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '3800'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '5200'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '6'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '12'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR5'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '65W'],
                    ['name' => '[CPU] Công suất cơ bản', 'value' => '65W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'AMD Precision Boost, AMD Overdrive'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '5nm'],
                ]
            ],
            [
                'name' => 'AMD Ryzen 7 5800X',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'AMD'],
                    ['name' => 'Model', 'value' => 'CPUR75800X'],
                    ['name' => 'Price', 'value' => '8900000'],
                    ['name' => 'Deal Price', 'value' => '8500000'],
                    ['name' => 'Rating', 'value' => '4.8'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '8390000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-08'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-12'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/AMD/2/Image7.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/AMD/Thumb7.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/AMD/2/Image7.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'AM4'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '3800'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '4700'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '8'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '16'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR4'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '105W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'AMD Precision Boost, AMD Overdrive'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '7nm'],
                ]
            ],
            [
                'name' => 'AMD Ryzen 9 5900X',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'AMD'],
                    ['name' => 'Model', 'value' => 'CPUR95900X'],
                    ['name' => 'Price', 'value' => '11900000'],
                    ['name' => 'Deal Price', 'value' => '11200000'],
                    ['name' => 'Rating', 'value' => '5'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '10900000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-10'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-15'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/AMD/3/Image8.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/AMD/Thumb9.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/AMD/3/Image8.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'AM4'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '3700'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '4800'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '12'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '24'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR4'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '105W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'AMD Precision Boost, AMD Overdrive'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '7nm'],
                ]
            ],
            [
                'name' => 'AMD Ryzen 5 7600X',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'AMD'],
                    ['name' => 'Model', 'value' => 'CPUR57600X'],
                    ['name' => 'Price', 'value' => '6700000'],
                    ['name' => 'Deal Price', 'value' => '6400000'],
                    ['name' => 'Rating', 'value' => '4.6'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '6290000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-12'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-13'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/AMD/4/Image9.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/AMD/Thumb5.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/AMD/4/Image9.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'AM5'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '4400'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '5600'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '6'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '12'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR5'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '128GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '105W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'AMD Precision Boost, AMD Overdrive'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '5nm'],
                ]
            ],
            [
                'name' => 'AMD Ryzen 3 4300G',
                'category_id' => 3,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'AMD'],
                    ['name' => 'Model', 'value' => 'CPUR34300G'],
                    ['name' => 'Price', 'value' => '2600000'],
                    ['name' => 'Deal Price', 'value' => '2400000'],
                    ['name' => 'Rating', 'value' => '4.2'],
                    ['name' => 'Loại linh kiện', 'value' => 'cpu'],
                    ['name' => 'Sale Price', 'value' => '2290000'],
                    ['name' => 'Sale Start Date', 'value' => '2024-11-14'],
                    ['name' => 'Sale End Date', 'value' => '2024-11-16'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/pc-parts/cpu/AMD/5/Image10.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/pc-parts/cpu/AMD/Thumb3.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/pc-parts/cpu/AMD/5/Image10.jpg'],
                    ['name' => '[CPU] Socket', 'value' => 'AM4'],
                    ['name' => '[CPU] Tốc độ cơ bản', 'value' => '3800'],
                    ['name' => '[CPU] Tốc độ tối đa', 'value' => '4000'], 
                    ['name' => '[CPU] Nhân CPU', 'value' => '4'],
                    ['name' => '[CPU] Luồng CPU', 'value' => '8'],
                    ['name' => '[CPU] Bộ nhớ hỗ trợ', 'value' => 'DDR4'],
                    ['name' => '[CPU] Kích thước bộ nhớ tối đa', 'value' => '64GB'],
                    ['name' => '[CPU] Số kênh bộ nhớ tối đa', 'value' => '2'],
                    ['name' => '[CPU] Điện áp tiêu thụ tối đa', 'value' => '65W'],
                    ['name' => '[CPU] Tính năng', 'value' => 'AMD Precision Boost, AMD Overdrive'],
                    ['name' => '[CPU] Thuật in thạch bản', 'value' => '7nm'],
                ]
            ]
        ];
        foreach ($cpus as $cpuData) {
            $cpu = Cpu::create([
                'name' => $cpuData['name'],
                'category_id' => $cpuData['category_id'],
            ]);
        
            foreach ($cpuData['attributes'] as $attr) {
                $attribute = Attribute::firstOrCreate(['name' => $attr['name']]);
                CpuAttribute::create([
                    'cpu_id' => $cpu->id,
                    'attribute_id' => $attribute->id,
                    'value' => $attr['value'],
                ]);
            }
        }
    }
}
