<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Laptop;
use App\Models\Attribute;
use App\Models\LaptopAttribute;

class LaptopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $laptops = [
            [
                'name' => 'Laptop Asus ROG Strix G16 G614JI',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1394'],
                    ['name' => 'Price', 'value' => '54990000'],
                    ['name' => 'Deal Price', 'value' => '42990000'],
                    ['name' => 'Sale Price', 'value' => '40990000'],
                    ['name' => 'Rating', 'value' => '5'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/gaming/1/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/gaming/1/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/gaming/1/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/gaming/1/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/gaming/1/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/gaming/1/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/gaming/1/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i7-13650HX'],
                    ['name' => '[Laptop] Số nhân', 'value' => '14'],
                    ['name' => '[Laptop] Số luồng', 'value' => '20'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'upto 4.90 GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX 4060 8GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '16 inch 16:10'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'QHD+ (2560 x 1600, WQXGA)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '240Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => '3ms IPS-level, 500 nits, 100% DCI-P3, anti-glare display'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR5'],
                    ['name' => '[Laptop] Bus RAM', 'value' => '4800Mhz'],
                    ['name' => '[Laptop] Số khe cắm RAM', 'value' => '2'],
                    ['name' => '[Laptop] Hỗ trợ RAM tối đa', 'value' => '32GB'],
                    ['name' => '[Laptop] Pin', 'value' => '4-cell, 90WHrs'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB PCIe® 4.0 NVMe™ M.2 SSD'],
                    ['name' => '[Laptop] Dung lượng ổ cứng', 'value' => '512GB'],
                    ['name' => '[Laptop] Số khe ổ cứng', 'value' => '2'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '2.50 Kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Eclipse Gray'],
                    ['name' => '[Laptop] Camera', 'value' => '720P HD camera'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ]
            ],
            [
                'name' => 'Laptop Asus ROG Strix G16 G614JU-N4132W',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1377'],
                    ['name' => 'Price', 'value' => '41990000'],
                    ['name' => 'Deal Price', 'value' => '33990000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/gaming/1/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/gaming/1/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/gaming/1/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/gaming/1/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/gaming/1/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/gaming/1/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/gaming/1/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i7-13650HX'],
                    ['name' => '[Laptop] Số nhân', 'value' => '8'],
                    ['name' => '[Laptop] Số luồng', 'value' => '16'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'upto 4.90 GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX 4050 6GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '16 inch 16:10'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'QHD+ (2560 x 1600, WQXGA)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '240Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'IPS QHD+, 3ms, 100% DCI-P3, chống chói, G-Sync, Pantone Validated, ROG Nebula Display'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR5'],
                    ['name' => '[Laptop] Bus RAM', 'value' => '4800MHz'],
                    ['name' => '[Laptop] Số khe cắm RAM', 'value' => '2'],
                    ['name' => '[Laptop] Hỗ trợ RAM tối đa', 'value' => '32GB'],
                    ['name' => '[Laptop] Pin', 'value' => '4-cell, 90WHrs'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB M.2 NVMe PCIe 4.0 SSD (Trống 1 slot M.2 NVMe)'],
                    ['name' => '[Laptop] Dung lượng ổ cứng', 'value' => '512GB'],
                    ['name' => '[Laptop] Số khe ổ cứng', 'value' => '2'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '2.50 Kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Eclipse Gray'],
                    ['name' => '[Laptop] Camera', 'value' => '720P HD camera'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ],
            ],
            [
                'name' => 'Laptop Asus ROG Strix G16 G614JV-N4156W',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1366'],
                    ['name' => 'Price', 'value' => '40990000'],
                    ['name' => 'Deal Price', 'value' => '31990000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/gaming/2/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/gaming/2/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/gaming/2/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/gaming/2/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/gaming/2/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/gaming/2/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/gaming/2/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i7-13650HX'],
                    ['name' => '[Laptop] Số nhân', 'value' => '14'],
                    ['name' => '[Laptop] Số luồng', 'value' => '20'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'upto 4.90 GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24 MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX 4060 8GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '16 inch 16:10'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'QHD+ (2560 x 1600, WQXGA)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '240Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'IPS QHD+, 3ms, 100% DCI-P3, chống chói, 500 nits'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR5'],
                    ['name' => '[Laptop] Bus RAM', 'value' => '4800MHz'],
                    ['name' => '[Laptop] Số khe cắm RAM', 'value' => '2'],
                    ['name' => '[Laptop] Hỗ trợ RAM tối đa', 'value' => '32GB'],
                    ['name' => '[Laptop] Pin', 'value' => '4-cell, 90WHrs'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB PCIe® 4.0 NVMe™ M.2 SSD'],
                    ['name' => '[Laptop] Dung lượng ổ cứng', 'value' => '512GB'],
                    ['name' => '[Laptop] Số khe ổ cứng', 'value' => '2'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '2.50 Kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Eclipse Gray'],
                    ['name' => '[Laptop] Camera', 'value' => '720P HD camera'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ],
            ],
            [
                'name' => 'Laptop Asus TUF Gaming F15 FX507ZC4-HN095W',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1311'],
                    ['name' => 'Price', 'value' => '24999000'],
                    ['name' => 'Deal Price', 'value' => '19590000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/gaming/3/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops /gaming/3/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/gaming/3/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/gaming/3/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/gaming/3/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/gaming/3/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/gaming/3/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i5-12500H'],
                    ['name' => '[Laptop] Số nhân', 'value' => '12'],
                    ['name' => '[Laptop] Số luồng', 'value' => '16'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'upto 4.50 GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '18MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX™ 3050 4GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '15.6-inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'FHD (1920 x 1080)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '144Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'Value IPS-level, 250 nits, SRGB 63%, anti-glare display'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB (2x8GB)'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR4-3200'],
                    ['name' => '[Laptop] Số khe cắm RAM', 'value' => '2'],
                    ['name' => '[Laptop] Hỗ trợ RAM tối đa', 'value' => '32GB'],
                    ['name' => '[Laptop] Pin', 'value' => '4-cell, 56WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '2.20 Kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Xám'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ],
            ],
            [
                'name' => 'Laptop ASUS ROG Flow X16 GV601VV-NF044W',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1378'],
                    ['name' => 'Price', 'value' => '54990000'],
                    ['name' => 'Deal Price', 'value' => '50990000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/gaming/4/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/gaming/4/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/gaming/4/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/gaming/4/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/gaming/4/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/gaming/4/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets /img/products/laptops/gaming/4/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i9-13900H'],
                    ['name' => '[Laptop] Số nhân', 'value' => '14'],
                    ['name' => '[Laptop] Số luồng', 'value' => '20'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'upto 5.4 GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA Geforce RTX 4060 8GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '16 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'WQXGA (2560 x 1600)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '240Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'DCI-P3 100%, Glossy Display, Pantone Validated, ROG Nebula HDR Display, Cảm ứng'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR5-4800 SO-DIMM'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '1TB PCIe® 4.0 NVMe™ M.2 SSD'],
                    ['name' => '[Laptop] Pin', 'value' => '4-cell Li-ion, 90WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '2.20 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Đen'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ],
            ],
            [
                'name' => 'Laptop Asus ROG Strix G18 G814JIR-N6007W',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1336'],
                    ['name' => 'Price', 'value' => '70999000'],
                    ['name' => 'Deal Price', 'value' => '60990000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/gaming/5/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/gaming/5/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/gaming/5/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/gaming/5/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/gaming/5/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/gaming/5/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/gaming/5/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel® Core™ i9-14900HX'],
                    ['name' => '[Laptop] Số nhân', 'value' => '24'],
                    ['name' => '[Laptop] Số luồng', 'value' => '32'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '36MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX 4070 8GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '18 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'QHD+ ( 2560 x 1600)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '240Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => '3ms IPS-level, 500 nits, 100% DCI-P3, anti-glare display'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '32GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR5-5600 SO-DIMM'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '1TB PCIe® 4.0 NVMe™ M.2 SSD'],
                    ['name' => '[Laptop] Pin', 'value' => '4-cell, 90WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '3.00 Kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Eclipse Gray'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ],
            ],
            [
                'name' => 'Laptop Asus Zenbook Pro 14 Duo OLED UX8402VU-P1028W',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1306'],
                    ['name' => 'Price', 'value' => '69990000'],
                    ['name' => 'Deal Price', 'value' => '55990000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/gaming/9/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/gaming/5/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/gaming/9/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/gaming/9/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/gaming/9/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/gaming/9/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/gaming/9/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i9-13900H'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 5.4GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX 4050 6GB'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '14.5 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => '2.8K (2880 x 1800)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '120Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'OLED, 100% DCI-P3 color gamut, 550nits HDR peak brightness'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '32GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'LPDDR5'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '1TB M.2 NVMe PCIe 4.0 SSD'],
                    ['name' => '[Laptop] Pin', 'value' => '4 cell 76WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => 'N/A'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Đen'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ],
            ],
            [
                'name' => 'Laptop Asus Gaming ROG Zephyrus G14 GA403UU-QS101W',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1341'],
                    ['name' => 'Price', 'value' => '54990000'],
                    ['name' => 'Deal Price', 'value' => '50990000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/gaming/7/Thumb.jpg '],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/gaming/7/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/gaming/7/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/gaming/7/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/gaming/7/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/gaming/7/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/gaming/7/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'AMD Ryzen 9 8945HS'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 5.2 GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX 4050 6GB'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '14 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => '3K (2880 x 1800)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '120Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'OLED, 500nits, 100% DCI-P3, Glossy display'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '32GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'LPDDR5X 6400'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB PCIe® 4.0 NVMe™ M.2 SSD'],
                    ['name' => '[Laptop] Pin', 'value' => '4-Cells 73WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '1.5 Kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Trắng'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ],
            ],
            [
                'name' => 'Laptop Asus Vivobook 14 OLED A1405VA-KM095W',
                'category_id' => 2,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1263'],
                    ['name' => 'Price', 'value' => '21990000'],
                    ['name' => 'Deal Price', 'value' => '16790000'],
                    ['name' => 'Rating', 'value' => '4'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/vivobook/a1405va/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/vivobook/a1405va/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/vivobook/a1405va/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/vivobook/a1405va/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/vivobook/a1405va/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/vivobook/a1405va/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/vivobook/a1405va/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Office'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i5-13500H'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 4.7GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '18MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'Intel Iris Xe Graphics'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '14 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => '2.8K (2880 x 1800)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '90Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'OLED, 100% DCI-P3, 600nits HDR'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => '8GB DDR4 on board + 8GB DDR4 SO-DIMM'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB M.2 NVMe PCIe 3.0 SSD'],
                    ['name' => '[Laptop] Pin', 'value' => '3 cell / 50WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '1.6 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Bạc'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ]
            ],
            [
                'name' => 'Laptop Asus Vivobook 15 X1504VA NJ070W',
                'category_id' => 2,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1277'],
                    ['name' => 'Price', 'value' => '19990000'],
                    ['name' => 'Deal Price', 'value' => '15190000'],
                    ['name' => 'Rating', 'value' => '1'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/vivobook/x1504va/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/vivobook/x1504va/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/vivobook/x1504va/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/vivobook/x1504va/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/vivobook/x1504va/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/vivobook/x1504va/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/vivobook/x1504va/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Office'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i5-1335U'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 4.60GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '12MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'Intel Iris Xe Graphics'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '15.6 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'FHD (1920 x 1080)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '60Hz'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => '8GB DDR4 on board + 8GB DDR4 SO-DIMM'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB M.2 NVMe PCIe 3.0 SSD'],
                    ['name' => '[Laptop] Pin', 'value' => '3-cell / 42WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '1.70 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Xanh'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ]
            ],
            [
                'name' => 'Laptop Asus Vivobook 15 X1504ZA-NJ582W',
                'category_id' => 2,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Asus'],
                    ['name' => 'Model', 'value' => 'NBAS1309'],
                    ['name' => 'Price', 'value' => '12990000'],
                    ['name' => 'Deal Price', 'value' => '9790000'],
                    ['name' => 'Rating', 'value' => '1'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/vivobook/x1504za/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/vivobook/x1504za/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/vivobook/x1504za/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/vivobook/x1504za/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/vivobook/x1504za/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/vivobook/x1504za/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/vivobook/x1504za/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Office'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i3-1215U'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 4.40GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '10MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'Intel UHD Graphics'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '15.6 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'FHD (1920 x 1080)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '60Hz'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '8GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => '8GB DDR4 on board 3200MHz'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB M.2 NVMe PCIe 3.0 SSD'],
                    ['name' => '[Laptop] Pin', 'value' => '3-cell / 42WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '1.70 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Bạc'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ]
            ],
            [
                'name' => 'Laptop Lenovo Yoga Slim 6 14IRH8 OLED 83E00008VN',
                'category_id' => 2,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Lenovo'],
                    ['name' => 'Model', 'value' => 'NBLN0766'],
                    ['name' => 'Price', 'value' => '26990000'],
                    ['name' => 'Deal Price', 'value' => '23690000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/lenovo/yoga_slim_6/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/lenovo/yoga_slim_6/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/lenovo/yoga_slim_6/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/lenovo/yoga_slim_6/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/lenovo/yoga_slim_6/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/len ovo/yoga_slim_6/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/lenovo/yoga_slim_6/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Office'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i7-13700H'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 5.0GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'Intel Iris Xe Graphics'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '14 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'WUXGA (1920x1200)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '60Hz'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'OLED, 100% DCI-P3, Eyesafe®, Dolby® Vision™, DisplayHDR™ True Black 500'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'LPDDR5x-5200 Soldered'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB SSD M.2 2242 PCIe 4.0x4 NVMe'],
                    ['name' => '[Laptop] Pin', 'value' => '3-cell / 65Wh'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '1.35 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Xám'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home Single Language + Office Home & Student 2021']
                ]
            ],
            [
                'name' => 'Laptop Lenovo V14 G4 IRU 83A000BGVN',
                'category_id' => 2,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Lenovo'],
                    ['name' => 'Model', 'value' => 'NBLN0851'],
                    ['name' => 'Price', 'value' => '14990000'],
                    ['name' => 'Deal Price', 'value' => '13490000'],
                    ['name' => 'Rating', 'value' => '1'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/lenovo/v14/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/lenovo/v14/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/lenovo/v14/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/lenovo/v14/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/lenovo/v14/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/lenovo/v14/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/lenovo/v14/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Office'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i5-13420H'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 4.6GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '12MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'Integrated Intel UHD Graphics'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '14 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'FHD (1920x1080)'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'IPS, Anti-glare, 45% NTSC'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => '8GB onboard + 1 khe rời DDR4 3200MHz'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB SSD M.2 2242 PCIe 4.0x4 NVMe'],
                    ['name' => '[Laptop] Pin', 'value' => '38Wh'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '1.43 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Iron Gray'],
                    ['name' => '[Laptop] OS', 'value' => 'NoOS']
                ]
            ],
            [
                'name' => 'Laptop Acer Swift Go SFG14-72-73YV NX.KRKSV.005',
                'category_id' => 2,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Acer'],
                    ['name' => 'Model', 'value' => 'NBAC0419TL'],
                    ['name' => 'Price', 'value' => '26990000'],
                    ['name' => 'Deal Price', 'value' => '19999000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/acer/swiftgo/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/acer/swiftgo/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/acer/swiftgo/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/acer/swiftgo/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/acer/swiftgo/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/acer/swiftgo/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/acer/swiftgo/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Office'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core Ultra 7 155H'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 4.8GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'Intel Arc Graphics'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '14 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => '2.2K (2240x1400)'],
                    ['name' => '[Laptop] Công nghệ màn hình', 'value' => 'IPS, sRGB 100%'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'LPDDR5x (không nâng cấp được)'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB PCIe NVMe SSD'],
                    ['name' => '[Laptop] Pin', 'value' => '3 cell 65Wh Li-ion'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '1.3 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Bạc'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home + Office Home & Student 2021']
                ]
            ],
            [
                'name' => 'Laptop Acer Gaming Nitro V 16 ProPanel ANV16-41-R7EN NH.QP2SV.004',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Acer'],
                    ['name' => 'Model', 'value' => 'NBAC0433'],
                    ['name' => 'Price', 'value' => '28790000'],
                    ['name' => 'Deal Price', 'value' => '25990000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/acer/nitro _v16/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/acer/nitro_v16/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/acer/nitro_v16/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/acer/nitro_v16/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/acer/nitro_v16/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/acer/nitro_v16/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/acer/nitro_v16/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'AMD Ryzen 7 8845HS'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'up to 5.10 GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '8 MB L2, up to 16MB L3'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX 3050 6GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '16 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'WUXGA (1920x1200)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '165Hz'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR5 5600Mhz'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512GB PCIe NVMe SSD (nâng cấp tối đa 4T SSD)'],
                    ['name' => '[Laptop] Pin', 'value' => '4 cell - 57 Wh'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '2.5 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Obsidian black'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home']
                ]
            ],
            [
                'name' => 'Laptop Dell Inspiron 14 N5440-C5U165W11IBD2',
                'category_id' => 2,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Dell'],
                    ['name' => 'Model', 'value' => 'NBDE0938'],
                    ['name' => 'Price', 'value' => '27190000'],
                    ['name' => 'Deal Price', 'value' => '24590000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/dell/inspiron_14/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/dell/inspiron_14/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/dell/inspiron_14/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/dell/inspiron_14/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/dell/inspiron_14/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/dell/inspiron_14/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/dell/inspiron_14/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Office'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core 5 processor 120U'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'Up to 5.00GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm ', 'value' => '12MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce MX570A 2GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '14.0 Inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => '2.2K (2240x1400)'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR5 5200 MHz (2 khe 8 GB)'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '512 GB SSD NVMe PCIe'],
                    ['name' => '[Laptop] Pin', 'value' => '4 Cell 54WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '1.56 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Xanh'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home SL + Office Home and Student 2021']
                ]
            ],
            [
                'name' => 'Laptop Dell Gaming G15 5530 i7HX161W11GR4060',
                'category_id' => 1,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Dell'],
                    ['name' => 'Model', 'value' => 'NBDE0944'],
                    ['name' => 'Price', 'value' => '42990000'],
                    ['name' => 'Deal Price', 'value' => '38490000'],
                    ['name' => 'Rating', 'value' => '0'],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/laptops/dell/gaming_g15/Thumb.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/laptops/dell/gaming_g15/Thumb_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/laptops/dell/gaming_g15/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/laptops/dell/gaming_g15/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/laptops/dell/gaming_g15/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/laptops/dell/gaming_g15/Image4.jpg'],
                    ['name' => 'Image5', 'value' => '/assets/img/products/laptops/dell/gaming_g15/Image5.jpg'],
                    ['name' => '[Laptop] Loại laptop', 'value' => 'Gaming'],
                    ['name' => '[Laptop] Vi xử lý', 'value' => 'Intel Core i7-13650HX'],
                    ['name' => '[Laptop] Tốc độ tối đa', 'value' => 'Up to 4.90GHz'],
                    ['name' => '[Laptop] Bộ nhớ đệm', 'value' => '24MB'],
                    ['name' => '[Laptop] Card đồ hoạ', 'value' => 'NVIDIA GeForce RTX 4060 8GB GDDR6'],
                    ['name' => '[Laptop] Kích thước màn hình', 'value' => '15.6 inch'],
                    ['name' => '[Laptop] Độ phân giải', 'value' => 'FHD (1920 x 1080)'],
                    ['name' => '[Laptop] Tần số quét', 'value' => '165Hz'],
                    ['name' => '[Laptop] Dung lượng RAM', 'value' => '16GB (8GBx2)'],
                    ['name' => '[Laptop] Loại RAM', 'value' => 'DDR5 4800MHz'],
                    ['name' => '[Laptop] Ổ cứng', 'value' => '1TB SSD M.2 PCIe'],
                    ['name' => '[Laptop] Pin', 'value' => '6 Cell 86 WHrs'],
                    ['name' => '[Laptop] Cân nặng', 'value' => '2.81 kg'],
                    ['name' => '[Laptop] Màu sắc', 'value' => 'Xám Đen'],
                    ['name' => '[Laptop] OS', 'value' => 'Windows 11 Home SL + Office Home and Student 2021']
                ]
            ],
        ];

        foreach ($laptops as $laptopData) {
            $laptop = Laptop::create([
                'name' => $laptopData['name'],
                'category_id' => $laptopData['category_id'],
            ]);

            foreach ($laptopData['attributes'] as $attr) {
                $attribute = Attribute::firstOrCreate(['name' => $attr['name']]);
                LaptopAttribute::create([
                    'laptop_id' => $laptop->id,
                    'attribute_id' => $attribute->id,
                    'value' => $attr['value'],
                ]);
            }
        }
    }
}
