<?php

namespace Database\Seeders;

use App\Models\Attribute as ModelsAttribute;
use App\Models\Media;
use App\Models\MediaAttribute;
use App\Models\Attribute;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MediaSeeder extends Seeder
{
    public function run():void
    {

        $media = [
            [
                'name' => 'Logitech StreamCam',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Logitech'],
                    ['name' => 'Model', 'value' => 'StreamCam'],
                    ['name' => 'Price', 'value' => 4590000],
                    ['name' => 'Deal Price', 'value' => 4290000],
                    ['name' => 'Sale Price', 'value' => 3990000],
                    ['name' => 'Rating', 'value' => 4.8],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 50],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/webcam/1/Thumb1.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/webcam/1/Thumb1_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/webcam/1/Image1.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Webcam'],
                    ['name' => '[Media] Kết nối', 'value' => 'USB-C'],
                    ['name' => '[Media] Tính năng', 'value' => 'Full HD 1080p, Autofocus'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Plastic'],
                    ['name' => '[Media] Trọng lượng', 'value' => '150g'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'USB-powered'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB 3.0'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'Tripod, USB Cable'],
                ],
            ],
            [
                'name' => 'Blue Yeti Microphone',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Blue'],
                    ['name' => 'Model', 'value' => 'Yeti'],
                    ['name' => 'Price', 'value' => 4990000],
                    ['name' => 'Deal Price', 'value' => 4690000],
                    ['name' => 'Sale Price', 'value' => 4490000],
                    ['name' => 'Rating', 'value' => 4.7],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 40],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/microphone/1/Thumb1.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/microphone/1/Thumb1_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/microphone/1/Image1.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/microphone/1/Image2.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Microphone'],
                    ['name' => '[Media] Kết nối', 'value' => 'USB'],
                    ['name' => '[Media] Tính năng', 'value' => 'Multiple recording patterns, Mute button'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Metal'],
                    ['name' => '[Media] Trọng lượng', 'value' => '1.2kg'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'USB-powered'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB, 3.5mm Jack'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'USB Cable, Desktop Stand'],
                ],
            ],
            [
                'name' => 'HyperX QuadCast S',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'HyperX'],
                    ['name' => 'Model', 'value' => 'QuadCast S'],
                    ['name' => 'Price', 'value' => 4990000],
                    ['name' => 'Deal Price', 'value' => 4690000],
                    ['name' => 'Sale Price', 'value' => 4290000],
                    ['name' => 'Rating', 'value' => 4.8],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 55],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/microphone/2/Thumb2.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/microphone/2/Thumb2_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/microphone/2/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/media/microphone/2/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/media/microphone/2/Image3.jpg'],
                    ['name' => 'Image4', 'value' => '/assets/img/products/media/microphone/2/Image4.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Microphone'],
                    ['name' => '[Media] Kết nối', 'value' => 'USB, 3.5mm Jack'],
                    ['name' => '[Media] Tính năng', 'value' => 'RGB Lighting, Anti-vibration mount'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Metal, Plastic'],
                    ['name' => '[Media] Trọng lượng', 'value' => '254g'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'USB-powered'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB, 3.5mm Jack'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'Anti-vibration mount, USB Cable'],
                ],
            ],
            [
                'name' => 'JBL Charge 5',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'JBL'],
                    ['name' => 'Model', 'value' => 'Charge 5'],
                    ['name' => 'Price', 'value' => 5990000],
                    ['name' => 'Deal Price', 'value' => 5690000],
                    ['name' => 'Sale Price', 'value' => 5390000],
                    ['name' => 'Rating', 'value' => 4.8],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 60],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/speaker/1/Thumb1.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/speaker/1/Thumb1_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/speaker/1/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/media/speaker/1/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/media/speaker/1/Image3.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Speaker'],
                    ['name' => '[Media] Kết nối', 'value' => 'Bluetooth, USB'],
                    ['name' => '[Media] Tính năng', 'value' => 'Waterproof, 20-hour battery life'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Fabric, Plastic'],
                    ['name' => '[Media] Trọng lượng', 'value' => '960g'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'Built-in rechargeable battery'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB-C, 3.5mm Aux'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'Charging Cable, User Manual'],
                ],
            ],
            [
                'name' => 'Elgato Stream Deck MK.2',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Elgato'],
                    ['name' => 'Model', 'value' => 'Stream Deck MK.2'],
                    ['name' => 'Price', 'value' => 6490000],
                    ['name' => 'Deal Price', 'value' => 6190000],
                    ['name' => 'Sale Price', 'value' => 5990000],
                    ['name' => 'Rating', 'value' => 4.9],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 45],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/controller/1/Thumb1.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/controller/1/Thumb1_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/controller/1/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/media/controller/1/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/media/controller/1/Image3.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Controller'],
                    ['name' => '[Media] Kết nối', 'value' => 'USB-C'],
                    ['name' => '[Media] Tính năng', 'value' => 'Customizable Keys, Multi-action'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Plastic'],
                    ['name' => '[Media] Trọng lượng', 'value' => '210g'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'USB-powered'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB-C'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'USB Cable, Adjustable Stand'],
                ],
            ],
            [
                'name' => 'Razer Kiyo Pro',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Razer'],
                    ['name' => 'Model', 'value' => 'Kiyo Pro'],
                    ['name' => 'Price', 'value' => 4990000],
                    ['name' => 'Deal Price', 'value' => 4690000],
                    ['name' => 'Sale Price', 'value' => 4290000],
                    ['name' => 'Rating', 'value' => 4.7],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 60],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/webcam/2/Thumb2.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/webcam/2/Thumb2_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/webcam/2/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/media/webcam/2/Image1.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/media/webcam/2/Image1.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Webcam'],
                    ['name' => '[Media] Kết nối', 'value' => 'USB-C'],
                    ['name' => '[Media] Tính năng', 'value' => 'HDR, Autofocus, Adjustable Field of View'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Plastic'],
                    ['name' => '[Media] Trọng lượng', 'value' => '200g'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'USB-powered'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB-C'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'Privacy Cover, USB Cable'],
                ],
            ],
            // Webcam 2
            [
                'name' => 'AverMedia PW513',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'AverMedia'],
                    ['name' => 'Model', 'value' => 'PW513'],
                    ['name' => 'Price', 'value' => 5490000],
                    ['name' => 'Deal Price', 'value' => 5190000],
                    ['name' => 'Sale Price', 'value' => 4990000],
                    ['name' => 'Rating', 'value' => 4.6],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 45],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/webcam/3/Thumb3.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/webcam/3/Thumb3_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/webcam/3/Image1.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Webcam'],
                    ['name' => '[Media] Kết nối', 'value' => 'USB'],
                    ['name' => '[Media] Tính năng', 'value' => '4K Ultra HD, Wide-Angle Lens'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Plastic'],
                    ['name' => '[Media] Trọng lượng', 'value' => '280g'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'USB-powered'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'Mount Adapter, USB Cable'],
                ],
            ],
            // Speaker 1
            [
                'name' => 'JBL Charge 5',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'JBL'],
                    ['name' => 'Model', 'value' => 'Charge 5'],
                    ['name' => 'Price', 'value' => 3990000],
                    ['name' => 'Deal Price', 'value' => 3690000],
                    ['name' => 'Sale Price', 'value' => 3490000],
                    ['name' => 'Rating', 'value' => 4.8],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 70],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/speaker/0/Thumb0.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/speaker/0/Thumb0_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/speaker/0/Image1.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Speaker'],
                    ['name' => '[Media] Kết nối', 'value' => 'Bluetooth, AUX'],
                    ['name' => '[Media] Tính năng', 'value' => 'Waterproof, 20-hour Battery Life'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Plastic, Fabric'],
                    ['name' => '[Media] Trọng lượng', 'value' => '960g'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'Battery-powered'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB-C, AUX'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'Charging Cable, User Manual'],
                ],
            ],
            // Speaker 2
            [
                'name' => 'Sony SRS-XB43',
                'category_id' => 6,
                'attributes' => [
                    ['name' => 'Brand', 'value' => 'Sony'],
                    ['name' => 'Model', 'value' => 'SRS-XB43'],
                    ['name' => 'Price', 'value' => 5990000],
                    ['name' => 'Deal Price', 'value' => 5590000],
                    ['name' => 'Sale Price', 'value' => 5290000],
                    ['name' => 'Rating', 'value' => 4.9],
                    ['name' => 'On Top', 'value' => '1'],
                    ['name' => 'Tồn kho', 'value' => 30],
                    ['name' => 'Thumbnail', 'value' => '/assets/img/products/media/speaker/2/Thumb2.jpg'],
                    ['name' => 'Thumbnail Small', 'value' => '/assets/img/products/media/speaker/2/Thumb2_small.jpg'],
                    ['name' => 'Image1', 'value' => '/assets/img/products/media/speaker/2/Image1.jpg'],
                    ['name' => 'Image2', 'value' => '/assets/img/products/media/speaker/2/Image2.jpg'],
                    ['name' => 'Image3', 'value' => '/assets/img/products/media/speaker/2/Image3.jpg'],
                    ['name' => '[Media] Loại thiết bị', 'value' => 'Speaker'],
                    ['name' => '[Media] Kết nối', 'value' => 'Bluetooth, AUX'],
                    ['name' => '[Media] Tính năng', 'value' => 'Extra Bass, IP67 Waterproof'],
                    ['name' => '[Media] Chất liệu', 'value' => 'Plastic, Rubber'],
                    ['name' => '[Media] Trọng lượng', 'value' => '1.5kg'],
                    ['name' => '[Media] Nguồn cung cấp', 'value' => 'Battery-powered'],
                    ['name' => '[Media] Cổng kết nối', 'value' => 'USB-C, AUX'],
                    ['name' => '[Media] Phụ kiện đi kèm', 'value' => 'Charging Cable, User Manual'],
                ],
            ],
        ];

        foreach ($media as $mediaData) {
            $media = Media::create([
                'name' => $mediaData['name'],
                'category_id' => $mediaData['category_id'],
            ]);
        
            foreach ($mediaData['attributes'] as $attr) {
                $attribute = Attribute::firstOrCreate(['name' => $attr['name']]);
                MediaAttribute::create([
                    'media_id' => $media->id,
                    'attribute_id' => $attribute->id,
                    'value' => $attr['value'],
                ]);
            }
        }
    }
}
