services:
  sigmatech:
    container_name: sigmatech
    build:
      context: .
      target: php
    working_dir: /var/www
    ports:
     - 8080:8080
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - shared-net
      
networks:
  shared-net:
    external: true
